# Generated by Django 3.2.3 on 2021-05-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('clave_usuario', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos_cliente',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=70)),
                ('apellidos_empleado', models.CharField(max_length=70)),
                ('tipo_empleado', models.CharField(max_length=50)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chatapp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='chatapp.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatapp.usuario'),
        ),
        migrations.AlterField(
            model_name='salachat',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatapp.empleado'),
        ),
        migrations.DeleteModel(
            name='Operdador',
        ),
    ]
