# Generated by Django 3.2.3 on 2021-05-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20210529_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(default='cliente', max_length=30),
            preserve_default=False,
        ),
    ]
